### ISSUE TITLE
Unable to load native library: /data/app/com.google.vulkan.samples..../lib/arm/libvulkan_sample.so

### ISSUE THREAD

**Issue by pranaypatel512** [googlesamples/vulkan-basic-samples#14]
Hi,
After cloning the repository with all samples, I successfully sync my project with all example.
But while running any of example, every time I am getting below error:
`03-03 17:53:07.740 29275-29275/com.google.vulkan.samples.initframebuffers E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                            Process: com.google.vulkan.samples.initframebuffers, PID: 29275
                                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.vulkan.samples.initframebuffers/android.app.NativeActivity}: java.lang.IllegalArgumentException: Unable to load native library: /data/app/com.google.vulkan.samples.initframebuffers-2/lib/arm/libvulkan_sample.so
                                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                                             Caused by: java.lang.IllegalArgumentException: Unable to load native library: /data/app/com.google.vulkan.samples.initframebuffers-2/lib/arm/libvulkan_sample.so
                                                                                                at android.app.NativeActivity.onCreate(NativeActivity.java:182)
                                                                                                at android.app.Activity.performCreate(Activity.java:6259)
                                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
`

Can anyone help me to resolve this the error.

**Comment by ggfan** [comment]
Sorry for not seeing this issue: if you still have the problem, which android version and hardware platform you are using?

**Comment by ggfan** [comment]
Oh, everything is changed, may you re-check if it is still failing?  make sure pre-build shaderc code inside your ndk ( README.md ):
```java
$ cd ${ndk_root}/sources/third_party/shaderc
$ ../../../ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=Android.mk APP_STL:=gnustl_static APP_ABI=all NDK_TOOLCHAIN_VERSION:=clang libshaderc_combined -j16
```
we will fix the bugs in the upstream from here and on.  thank you for help

**Comment by pranaypatel512** [comment]
@ggfan Thanks for an update. I will update make changes and back to you.

**Comment by ggfan** [comment]
Great!  Oh, please add my user name when you report issues here, somehow this repo email notification was not set up -- I did not get email.

**Comment by ggfan** [comment]
closing this down, reopen when needed, thanks!
