### ISSUE TITLE
Building on Android is failed at precompiled shaders stage (HTTP Error 404: Not Found)

### ISSUE THREAD

**Issue by apnavik** [googlesamples/vulkan-basic-samples#37]
Following stage is failed, when I checked the ../../scripts/fetch_spirv_tools.py. It seems, URL is not valid anymore.

 $ python3 ./compile_shaders.py
 
 Error log:
 Downloading spirv-as binary from spirv-tools releases dir
Traceback (most recent call last):
  File "../../scripts/fetch_spirv_tools.py", line 64, in <module>
    with urllib.request.urlopen(SPIRV_TOOLS_COMPLETE_URL, context=ssl._create_unverified_context()) as response, open(SPIRV_TOOLS_OUTFILENAME, 'wb') as out_file:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "./compile_shaders.py", line 21, in <module>
    subprocess.check_call(args)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.8', '../../scripts/fetch_spirv_tools.py', 'SPIRV-Tools-master-linux-RelWithDebInfo.zip']' returned non-zero exit status 1.

**Comment by apnavik** [comment]
@olvaffe can you please help assign it to right person. or if you know any solution for problem. 
Appreciate your help
